Parameters: ['/Peregrine/FCPU/TMGR/TCS_DECKD_1/TCS_DECKD_1', '/Peregrine/FCPU/TMGR/TCS_DECKD_2/TCS_DECKD_2', '/Peregrine/FCPU/TMGR/TCS_DECKD_3/TCS_DECKD_3', '/Peregrine/payloads/iris/iris-payload-tm-rs422', '/Peregrine/payloads/iris/iris-payload-tm-wlan', '/Peregrine/PL1/SLIPsvc@3Status', '/Peregrine/PL1/WIFIsvc@3Status']
Subscribing to updates of parameter: /Peregrine/FCPU/TMGR/TCS_DECKD_1/TCS_DECKD_1
Subscribing to updates of parameter: /Peregrine/FCPU/TMGR/TCS_DECKD_2/TCS_DECKD_2
/Peregrine/FCPU/TMGR/TCS_DECKD_1/TCS_DECKD_1: None
Subscribing to updates of parameter: /Peregrine/FCPU/TMGR/TCS_DECKD_3/TCS_DECKD_3
/Peregrine/FCPU/TMGR/TCS_DECKD_2/TCS_DECKD_2: None
Subscribing to updates of parameter: /Peregrine/payloads/iris/iris-payload-tm-rs422
/Peregrine/FCPU/TMGR/TCS_DECKD_3/TCS_DECKD_3: None
Subscribing to updates of parameter: /Peregrine/payloads/iris/iris-payload-tm-wlan
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
/Peregrine/payloads/iris/iris-payload-tm-wlan: None
Subscribing to updates of parameter: /Peregrine/PL1/SLIPsvc@3Status
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
Subscribing to updates of parameter: /Peregrine/PL1/WIFIsvc@3Status
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:44.366000-05:00] /Peregrine/payloads/iris/iris-payload-tm-rs422: b'\xff\x00\x00\x00' 	->	 b'\xff\x00\x00\x00'
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:46.184000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVEERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE

[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/SLIPsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVE
[2022-11-11 09:46:51.186000-05:00] /Peregrine/PL1/WIFIsvc@3Status: 0 	->	 ACTIVEERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 216, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 228, in _wrap_sni_socket
    return context.wrap_socket(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/osiris/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_http.py", line 298, in read_headers
    line = recv_line(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv_line
    c = recv(sock, 1)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_socket.py", line 93, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error
ERROR:root:WebSocket error
Traceback (most recent call last):
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_app.py", line 231, in run_forever
    self.sock.connect(
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/osiris/.pyenv/versions/py_irisbackendv3/lib/python3.8/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error
